---
name:               "Publish Docker Image"
description:        "Build and publish a perl-tester Docker image to Docker Hub"

inputs:
  base:
    description:    "Docker base image tag"
    required:       true
  hub-password:
    description:    "Docker Hub password"
    required:       true
  hub-username:
    description:    "Docker Hub username"
    required:       true
  tags:
    description:    "Docker image tags (comma-separated)"
    required:       true

runs:
  using:            "composite"
  steps:
    - name:         "Publish to Registry"
      uses:         elgohr/Publish-Docker-Github-Action@v5
      with:
        buildargs:  "BASE=${{ inputs.base }}"
        dockerfile: "Dockerfile"
        name:       "perldocker/perl-tester"
        password:   "${{ inputs.hub-password }}"
        tags:       "${{ inputs.tags }}"
        username:   "${{ inputs.hub-username }}"
        no_push:    >-
          ${{ !(github.repository_owner == 'Perl' && github.ref_name == 'main' &&
          (github.event_name == 'push' || github.event_name == 'schedule' ||
          github.event_name == 'workflow_dispatch' ||
          github.event.pull_request.merged == true)) }}
